$ cat go-binary-release.yml

name: build-go-binary

on:
  release:
    types: [created, published]

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows] # 需要打包的系统
        goarch: [amd64] # 需要打包的架构

    steps:
      - uses: actions/checkout@v4.1.7
      - uses: wangyoucao577/go-release-action@v1.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # 一个默认的变量，用来实现往 Release 中添加文件
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.21.6 # 可以指定编译使用的 Golang 版本
          binary_name: "Bilibili_Downloader" # 可以指定二进制文件的名称          
          extra_files: README.md # 需要包含的额外文件
          compress_assets: OFF
          ldflags: -s -w
